[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shotgen-monorepo"
version = "1.0.1"
description = "Monorepo workspace for shotgen-core and shotgen-gpu"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jesus Ochoa", email = "jochoacontre@mun.ca" }]

[tool.setuptools]
packages = []
